- name: variables at task levels
  hosts: localhost
  #this variables are parent or play level
  vars:
  - money: "10000 RS"
    land: "400 hectars"
    tasks:
    - name: inherit  values from play
      ansible.builtin.debug:
        msg: "MONEY: {{money}}, LAND: {{land}}"
    - name: inherit the values from play and add and override
      vars: 
      - money: "200000 RS"
        houses: "3 houses"
      ansible.builtin.debug:
        msg: "MONEY: {{money}}, LAND: {{land}}, houses: {{houses}}"


