- name: create user
  hosts: localhost
  tasks:
  - name: check username exit or not
  # when u want to run linux  commands directly, i.e in the case of ansible module not available.
    ansible.builtin.command: id robhoshop
    register: output #output is variable
  - name: print this output
    ansible.builtin.debug: 
      msg:"{{output}}"

