- name: create user
  hosts: localhost
  tasks:
  - name: check username exit or not
  # when u want to run linux  commands directly, i.e in the case of ansible module not available.
  #when user doesnt exit ansible treating it as failure and comeout bydefault
  #Ignore_errors: true
    ansible.builtin.command: id robhoshop
    register: output  #output is variable
    ignore_errors: true
  - name: print this output
    ansible.builtin.debug: 
      msg: "output is:{{output}}"
  - name: print exist status
    ansible.builtin.debug:
      msg: "{{output.rc}}"
  - name: create user robhoshop
    become: yes   #we need sudo acesses at this level and if u give at play level it applies at every task.
    ansible.builtin.user:         #user module
      name: robhoshop
    when: output.rc != 0          ##when condition in ansible.

