- name: simple conditions
  hosts: localhost
  vars:
    name: devopzs1   #DevOps
  tasks:
  - name: run if the name is devops
    ansible.builtin.debug:
      msg: "{{name}}"
    when: name == "DevOps"   #ansible when condition.
