- name: install packages
  hosts: localhost
  become: yes
  tasks:
  - name: install packages
    ansible.builtin.yum:
      name: "{{item}}"
      state: started
    loop:
    - nginx
    - postfix
    - cyrus-sasl-plain
    - mailx                 #install packages through loops