- name: variables from files
  hosts: localhost # manaing the ansible  itself
  vars_files:
  - varieables.yaml
  tasks:
  - name: print the variables
    ansible.builtin.debug:
      msg: "we are learning {{NAME}}, duration is {{DURATION}},  trainer is {{TRAINER}}"

    